server:
  port: 8089

spring:
  application:
    name: luzhe-service

eureka:
  client:
    registry-fetch-interval-seconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka/,http://127.0.0.1:10087/eureka/
  # 将自己注册到eureka
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enable: true
# 负载均衡
#ProductService:
#  ribbon:
#    listOfServers: http://127.0.0.1:8088
